artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://archive.ics.uci.edu/ml/machine-learning-databases/wine-quality/winequality-red.csv
  local_data_file: artifacts/data_ingestion/winequality-red.csv
  unzip_dir: artifacts/data_ingestion


data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  data_path: artifacts/data_ingestion/winequality-red.csv


data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/winequality-red.csv
  preprocessor_path: artifacts/data_transformation/preprocessor.joblib


model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_ingestion/winequality-red.csv
  model_name: model.joblib
  test_size: 0.2
  target_column: quality


model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_ingestion/winequality-red.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json
  target_column: quality
  mlflow_uri: sqlite:///mlflow.db